export const FOCUS_VISIBLE_OUTLINE = `focus:outline-none focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-purple-500/70`

export const COLLECTIVE_NOUNS = [
  'murder',
  'cackle',
  'parliament',
  'shrewdness',
  'raft',
  'scurry',
  'wake',
  'battery',
  'muster',
  'walk',
  'coterie',
  'mutation',
  'memory',
  'skulk',
  'scold',
  'hover',
  'charm',
  'mob',
  'generation',
  'kaleidoscope',
  'family',
  'glaring',
  'rhumba',
  'mess',
]
